repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.257'
    hooks:
      - id: ruff
        args: [--fix, --exit-zero]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
