from setuptools import find_packages, setup

setup(
    name='GravNN',
    packages=find_packages(),
    version='0.1.0',
    description='GravNN Package',
    author='John M',
    license='MIT',
    setup_requires=[
                    'numpy == 1.21.0',
                    'matplotlib',
                    'numba',
                    'pandas',
                    'tensorflow>=2.6',
                    'sklearn',
                    'plotly',
                    'dash',
                    'trimesh == 3.9.31',
                    'sigfig',
                    'tqdm',
                    'colorama',
                    'tensorflow_model_optimization',
                    'kaleido',
                    'rtree',
                    'pooch',
                    'seaborn',
                    'spicepy',
                    'sphinx',
                    "sphinx_rtd_theme",
                    "sphinx-gallery"],
    install_requires=[
                    'numpy == 1.21.0',
                    'matplotlib',
                    'numba',
                    'pandas',
                    'tensorflow>=2.6',
                    'sklearn',
                    'plotly',
                    'dash',
                    'trimesh == 3.9.31',
                    'sigfig',
                    'tqdm',
                    'colorama',
                    'tensorflow_model_optimization',
                    'kaleido',
                    'rtree',
                    'pooch',
                    'seaborn',
                    'spicepy',
                    'sphinx',
                    "sphinx_rtd_theme",
                    "sphinx-gallery"],
    tests_require=['pytest==4.4.1'],
    test_suite='tests',
)


